apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dashboard-microservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dashboard-microservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 85
