apiVersion: v1
kind: Service
metadata:
  name: dashboard-microservice
  labels:
    app: dashboard-microservice
spec:
  type: LoadBalancer
  selector:
    app: dashboard-microservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
